"""Eliminar Columna

Revision ID: cb5079494032
Revises: 3afe86086510
Create Date: 2022-10-16 10:18:39.792333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb5079494032'
down_revision = '3afe86086510'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'estado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('estado', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
